export default MUSCLES = [
  {id: 1, name: 'Pectoralis', muscleGroup: 1},
  {id: 2, name: 'Biceps brachii', muscleGroup: 2},
  {id: 3, name: 'Brachialis', muscleGroup: 2},
  {id: 4, name: 'Triceps brachii', muscleGroup: 2},
  {id: 5, name: 'Wrist Extensors', muscleGroup: 2},
  {id: 6, name: 'Wrist Flexors', muscleGroup: 2},
  {id: 7, name: 'Trapezius', muscleGroup: 3},
  {id: 8, name: 'Latissimus dorsi', muscleGroup: 3},
  {id: 9, name: 'Obliques', muscleGroup: 4},
  {id: 10, name: 'Quadriceps', muscleGroup: 5},
  {id: 11, name: 'Glutes', muscleGroup: 5},
  {id: 12, name: 'Deltoids', muscleGroup: 6},
  {id: 13, name: 'Lower Back', muscleGroup: 3},
  {id: 14, name: 'Rectus Abdominis', muscleGroup: 4},
  {id: 15, name: 'Gastrocnemius', muscleGroup: 5},
  {id: 16, name: 'Hamstrings', muscleGroup: 5},
  {id: 17, name: 'Soleus', muscleGroup: 5},
  {id: 18, name: 'Infraspinatus', muscleGroup: 6},
  {id: 19, name: 'Rotator Cuff', muscleGroup: 6}
];
